[git]

    PackageName = 'git'
    PackageDir = './git'

    [git.files]

        [git.files.config]
            Source = './git/config.toml'
            Target = '$HOME/.gitconfig'

    [git.setup]
        Instructions = [
            'No further setup required'
        ]
