[git]
    PackageName = 'Git'

    [git.links]

        [git.links.config]
            Source = 'git/config.toml'
            Target = '~/.gitconfig'

[zsh]
    PackageName = 'Zsh'

    [zsh.links]
        
        [zsh.links.aliases]
            Source = 'zsh/aliases.zsh'
            Target = '~/.aliases'

        [zsh.links.functions]
            Source = 'zsh/functions.zsh'
            Target = '~/.functions'

        [zsh.links.config]
            Source = 'zsh/config.zsh'
            Target = '~/.zshrc'

[vim]
    PackageName = 'Vim'
    
    [vim.links]
        
        [vim.links.config]
            Source = 'vim/config.vim'
            Target = '~/.vimrc'

[ssh]
    PackageName = 'Secure Shell'

    [ssh.setup]
        RequiredDirectories = [
            '~/.ssh'
        ]

    [ssh.links]

        [ssh.links.config]
            Source = 'ssh/config'
            Target = '~/.ssh/config'

        [ssh.links.known_hosts]
            Source = 'ssh/known_hosts'
            Target = '~/.ssh/known_hosts'

[nvim]
    PackageName = 'Neovim'

    [nvim.setup]
        RequiredDirectories = [
            '~/.config/nvim'
        ]

    [nvim.links]
        
        [nvim.links.init]
            Source = 'nvim/init.lua'
            Target = '~/.config/nvim/init.lua'

        [nvim.links.lua]
            Source = 'nvim/lua'
            Target = '~/.config/nvim/lua'
